"""Node system settings: package updates, DNS, time and remote syslog (commands and files faked)."""

import subprocess

import pytest

from app.core import host_system as hs

APT_LIST = """Listing... Done
base-files/noble-updates 13ubuntu10.5 amd64 [upgradable from: 13ubuntu10.4]
openssl/noble-updates,noble-security 3.0.13-0ubuntu3.6 amd64 [upgradable from: 3.0.13-0ubuntu3.5]
libvirt0/bookworm-security 9.0.0-4+deb12u2 amd64 [upgradable from: 9.0.0-4+deb12u1]
hyperlite/stable 2026.10.1 amd64 [upgradable from: 2026.09.1]
"""


@pytest.fixture()
def host(tmp_path, monkeypatch):
    calls = []
    answers = {}

    def run(argv, timeout=60, env=None):
        calls.append(argv)
        out = answers.get(tuple(argv[:2]), "")
        return subprocess.CompletedProcess(argv, 0, out, "")

    monkeypatch.setattr(hs, "_run", run)
    for name in (
        "RESOLV_CONF",
        "RESOLVED_DROPIN",
        "TIMESYNCD_DROPIN",
        "RSYSLOG_DROPIN",
        "REBOOT_REQUIRED",
        "REBOOT_PKGS",
        "APT_LISTS",
    ):
        monkeypatch.setattr(hs, name, tmp_path / name.lower())
    monkeypatch.setattr(hs.shutil, "which", lambda name: f"/usr/bin/{name}")
    return {"calls": calls, "answers": answers, "tmp": tmp_path}


def test_upgradable_packages_are_parsed_with_security_flag(host):
    host["answers"][("apt", "list")] = APT_LIST
    (host["tmp"] / "reboot_required").write_text("*** System restart required ***\n")
    (host["tmp"] / "reboot_pkgs").write_text("linux-image-6.1\nlibc6\nlibc6\n")
    u = hs.updates(refresh=True)
    assert host["calls"][0] == ["apt-get", "update"]
    assert [(p["nom"], p["securite"]) for p in u["paquets"]] == [
        ("base-files", False),
        ("openssl", True),
        ("libvirt0", True),
        ("hyperlite", False),
    ]
    assert u["paquets"][1]["depuis"] == "3.0.13-0ubuntu3.5"
    assert (u["redemarrage_requis"], u["paquets_redemarrage"]) == (True, ["libc6", "linux-image-6.1"])


def test_upgrade_names_the_packages_and_leaves_hyperlite_out(host, monkeypatch):
    monkeypatch.setattr(hs.Path, "is_dir", lambda self: True)
    cmd = hs.upgrade_command(["openssl", "hyperlite", "libvirt0"])
    assert cmd[:5] == ["systemd-run", "--quiet", "--collect", "--wait", "--pipe"]
    assert cmd[-2:] == ["openssl", "libvirt0"] and "--only-upgrade" in cmd and "hyperlite" not in cmd
    with pytest.raises(hs.SettingError, match="Nothing to upgrade"):
        hs.upgrade_command(["hyperlite"])
    with pytest.raises(hs.SettingError, match="Invalid package"):
        hs.upgrade_command(["openssl; reboot"])


def test_dns_follows_who_manages_resolv_conf(host):
    resolv = host["tmp"] / "resolv_conf"
    resolv.write_text("nameserver 1.1.1.1\nsearch lan\n")
    assert hs.dns() == {"gere_par": "fichier", "modifiable": True, "serveurs": ["1.1.1.1"], "recherche": ["lan"]}
    hs.set_dns(["9.9.9.9", "2620:fe::fe"], ["example.org"])
    assert resolv.read_text().endswith("nameserver 9.9.9.9\nnameserver 2620:fe::fe\nsearch example.org\n")

    resolv.write_text("# Generated by NetworkManager\nnameserver 10.0.0.1\n")
    with pytest.raises(hs.SettingError, match="next lease"):
        hs.set_dns(["9.9.9.9"], [])

    resolv.unlink()
    resolv.symlink_to("/run/systemd/resolve/stub-resolv.conf")
    hs.set_dns(["9.9.9.9"], [])
    assert (host["tmp"] / "resolved_dropin").read_text().endswith("[Resolve]\nDNS=9.9.9.9\n")
    assert host["calls"][-1] == ["systemctl", "restart", "systemd-resolved"]
    assert hs.dns()["serveurs"] == ["9.9.9.9"]

    for servers, search, message in [
        ([], [], "At least one"),
        (["dns.example.org"], [], "Invalid DNS server"),
        (["1.1.1.1"] * 4, [], "At most 3"),
        (["1.1.1.1"], ["bad domain"], "Invalid search domain"),
    ]:
        with pytest.raises(hs.SettingError, match=message):
            hs.set_dns(servers, search)


def test_time_zone_is_checked_against_the_system_list(host):
    host["answers"][("timedatectl", "show")] = "Timezone=Etc/UTC\nNTP=yes\nNTPSynchronized=no\n"
    host["answers"][("timedatectl", "list-timezones")] = "Etc/UTC\nEurope/Paris\n"
    hs.set_time("Europe/Paris", False, ["0.pool.ntp.org", "192.0.2.1"])
    assert ["timedatectl", "set-timezone", "Europe/Paris"] in host["calls"]
    assert ["timedatectl", "set-ntp", "false"] in host["calls"]
    assert (host["tmp"] / "timesyncd_dropin").read_text().endswith("NTP=0.pool.ntp.org 192.0.2.1\n")
    with pytest.raises(hs.SettingError, match="Unknown time zone"):
        hs.set_time("Mars/Olympus", None, None)
    with pytest.raises(hs.SettingError, match="Unknown time zone"):
        hs.set_time("Europe/Paris; reboot", None, None)


def test_remote_syslog_drop_in(host):
    hs.set_syslog("logs.example.org", 6514, "tcp")
    assert (host["tmp"] / "rsyslog_dropin").read_text().endswith("*.* @@logs.example.org:6514\n")
    assert hs.syslog()["cible"] == {"hote": "logs.example.org", "port": 6514, "protocole": "tcp"}
    hs.set_syslog("2001:db8::5", 514, "udp")
    assert hs.syslog()["cible"] == {"hote": "2001:db8::5", "port": 514, "protocole": "udp"}
    for host_, port, proto, message in [
        ("a b", 514, "udp", "Invalid syslog"),
        ("logs", 0, "udp", "port"),
        ("logs", 514, "http", "protocol"),
    ]:
        with pytest.raises(hs.SettingError, match=message):
            hs.set_syslog(host_, port, proto)
    hs.set_syslog(None, 514, "udp")
    assert hs.syslog()["cible"] is None


def test_api_is_admin_only_and_starts_one_upgrade_task(client, auth_headers, host, monkeypatch):
    import threading

    from app.core import tasks
    from app.routers import host_system as router

    host["answers"][("apt", "list")] = APT_LIST
    admin = auth_headers("root", "admin")
    assert client.get("/host/system/updates", headers=auth_headers("watcher", "observateur")).status_code == 403
    assert len(client.get("/host/system/updates", headers=admin).json()["paquets"]) == 4

    release = threading.Event()

    def fake_run(packages, log):
        log("Setting up openssl ...")
        release.wait(5)
        return 0

    monkeypatch.setattr(hs, "run_upgrade", fake_run)
    r = client.post("/host/system/updates/upgrade", json={"paquets": ["openssl"]}, headers=admin)
    assert r.status_code == 202
    assert client.post("/host/system/updates/upgrade", json={"paquets": ["openssl"]}, headers=admin).status_code == 409
    release.set()
    for _ in range(50):
        if tasks.task_status(r.json()["tache"]) == "termine":
            break
        threading.Event().wait(0.05)
    assert tasks.task_status(r.json()["tache"]) == "termine"
    assert any("Setting up openssl" in line["message"] for line in tasks.get_task_log(r.json()["tache"]))
    assert not router._upgrade_lock.locked()
    assert client.put("/host/system/dns", json={"serveurs": ["nope"]}, headers=admin).status_code == 422


def test_power_needs_the_typed_name_and_stops_guests_first(client, auth_headers, monkeypatch):
    import threading

    from app.core import tasks
    from app.routers import host_system as router

    admin = auth_headers("root", "admin")
    monkeypatch.setattr(router.socket, "gethostname", lambda: "hv1")
    monkeypatch.setattr(hs, "running_guests", lambda: [("vm", "web"), ("conteneur", "ct1")])
    scheduled, stopped = [], []
    monkeypatch.setattr(hs, "schedule_power", lambda action: scheduled.append(action))

    body = {"action": "reboot", "confirmation": "hv2"}
    r = client.post("/host/system/power", json=body, headers=admin)
    assert r.status_code == 422 and "(hv1)" in r.json()["detail"]
    r = client.post("/host/system/power", json=body | {"confirmation": "hv1"}, headers=admin)
    assert r.status_code == 409 and "web, ct1" in r.json()["detail"]
    assert (
        client.post(
            "/host/system/power", json=body | {"action": "halt", "confirmation": "hv1"}, headers=admin
        ).status_code
        == 422
    )
    assert (
        client.post("/host/system/power", json=body, headers=auth_headers("watcher", "observateur")).status_code == 403
    )

    def wait(task_id):
        for _ in range(100):
            if tasks.task_status(task_id) != "en_cours":
                return tasks.task_status(task_id)
            threading.Event().wait(0.02)

    monkeypatch.setattr(hs, "stop_guests", lambda guests, log: stopped.append(guests) or ["web"])
    r = client.post(
        "/host/system/power", json={"action": "poweroff", "confirmation": "hv1", "arreter_invites": True}, headers=admin
    )
    assert r.status_code == 202 and wait(r.json()["tache"]) == "echec" and scheduled == []

    monkeypatch.setattr(hs, "stop_guests", lambda guests, log: [])
    r = client.post(
        "/host/system/power", json={"action": "poweroff", "confirmation": "hv1", "arreter_invites": True}, headers=admin
    )
    assert wait(r.json()["tache"]) == "termine" and scheduled == ["poweroff"]


def test_power_is_scheduled_outside_the_service(host, monkeypatch):
    monkeypatch.setattr(hs.Path, "is_dir", lambda self: True)
    hs.schedule_power("reboot")
    assert host["calls"][-1] == ["systemd-run", "--quiet", "--collect", "--on-active=5", "systemctl", "reboot"]
    with pytest.raises(hs.SettingError):
        hs.schedule_power("halt")
    monkeypatch.setattr(hs.Path, "is_dir", lambda self: False)
    with pytest.raises(hs.SettingError, match="does not run systemd"):
        hs.schedule_power("reboot")


def test_stop_guests_reports_what_did_not_stop(monkeypatch):
    class Dom:
        def __init__(self, stays):
            self.stays, self.asked = stays, False

        def shutdown(self):
            self.asked = True

        def isActive(self):
            return self.stays

    doms = {"web": Dom(False), "db": Dom(True)}

    class Conn:
        def lookupByName(self, name):
            return doms[name]

        def close(self):
            pass

    import app.core.libvirt_utils as lu

    monkeypatch.setattr(lu, "open_conn", lambda node=None: Conn())
    monkeypatch.setattr(lu, "open_lxc_conn", lambda: Conn())
    lines = []
    left = hs.stop_guests([("vm", "web"), ("vm", "db")], lines.append, timeout_s=0.02, poll_s=0.01)
    assert left == ["db"] and doms["web"].asked and doms["db"].asked
    assert lines == ["Shutdown requested: web", "Shutdown requested: db"]
