import { useEffect, useState } from "react";
import { LogIn, ShieldCheck, KeyRound } from "lucide-react";
import { useAuthStore } from "../store/useAuthStore";
import HyperliteLogo from "../components/HyperliteLogo";
import { fetchSsoStatus } from "../api/client";

export default function LoginScreen() {
  const login = useAuthStore((s) => s.login);
  const loginWith2FA = useAuthStore((s) => s.loginWith2FA);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  // The button only appears if an IdP is configured AND enabled on the server side
  // (GET /auth/sso/status, public: the sign-in screen knows nothing about anyone
  // yet). A failure in /auth/sso/callback comes back here through "?sso_error=..."
  // (see app/routers/sso.py) instead of a raw error page.
  const [ssoEnabled, setSsoEnabled] = useState(false);
  useEffect(() => {
    fetchSsoStatus().then((r) => setSsoEnabled(!!r.enabled)).catch(() => {});
    const params = new URLSearchParams(window.location.search);
    const ssoError = params.get("sso_error");
    if (ssoError) {
      setError(ssoError);
      window.history.replaceState({}, "", window.location.pathname);
    }
  }, []);

  // 2FA: when /auth/login returns require_2fa, we switch to a second step (TOTP code
  // entry) instead of showing the password form again. preAuthToken carries the
  // proof that the password was correct, valid for 5 minutes (see security.py).
  const [preAuthToken, setPreAuthToken] = useState(null);
  const [code, setCode] = useState("");

  async function onSubmit(e) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const result = await login(username, password);
      if (result.require2FA) {
        setPreAuthToken(result.preAuthToken);
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function onSubmit2FA(e) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      await loginWith2FA(preAuthToken, code, username);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  if (preAuthToken) {
    return (
      <div className="flex h-screen items-center justify-center bg-anthracite-900">
        <form onSubmit={onSubmit2FA} className="card w-full max-w-sm p-6">
          <div className="mb-5 flex items-center gap-2">
            <ShieldCheck size={22} className="text-accent-blue" />
            <span className="text-base font-semibold tracking-wide text-anthracite-100">Two-step verification</span>
          </div>
          <p className="mb-3 text-sm text-anthracite-300">
            Enter the 6-digit code generated by your authenticator app.
          </p>
          <input
            aria-label="6-digit verification code" autoComplete="one-time-code"
            className="input text-center text-lg tracking-[0.4em]" autoFocus inputMode="numeric" maxLength={6}
            value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
          />
          {error && <p role="alert" className="mt-3 text-sm text-status-error">{error}</p>}
          <button type="submit" disabled={loading || code.length !== 6} className="btn-primary mt-5 w-full justify-center">
            <ShieldCheck size={15} /> {loading ? "Verifying..." : "Verify"}
          </button>
          <button
            type="button" className="mt-2 w-full text-center text-xs text-anthracite-400 hover:text-anthracite-200"
            onClick={() => { setPreAuthToken(null); setCode(""); setError(""); }}
          >
            Back
          </button>
        </form>
      </div>
    );
  }

  return (
    <div className="flex h-screen items-center justify-center bg-anthracite-900">
      <form onSubmit={onSubmit} className="card w-full max-w-sm p-6">
        <div className="mb-5 flex items-center gap-2">
          <HyperliteLogo size={32} className="rounded-md" />
          <span className="text-base font-semibold tracking-wide text-anthracite-100">HYPERLITE</span>
        </div>

        <label htmlFor="login-username" className="text-xs font-medium text-anthracite-300">Username</label>
        <input id="login-username" autoComplete="username" className="input mt-1 mb-3" autoFocus value={username} onChange={(e) => setUsername(e.target.value)} />

        <label htmlFor="login-password" className="text-xs font-medium text-anthracite-300">Password</label>
        <input id="login-password" autoComplete="current-password" type="password" className="input mt-1" value={password} onChange={(e) => setPassword(e.target.value)} />

        {error && <p role="alert" className="mt-3 text-sm text-status-error">{error}</p>}

        <button type="submit" disabled={loading} className="btn-primary mt-5 w-full justify-center">
          <LogIn size={15} /> {loading ? "Signing in..." : "Sign in"}
        </button>

        {ssoEnabled && (
          <>
            <div className="my-4 flex items-center gap-3 text-xs text-anthracite-400">
              <div className="h-px flex-1 bg-anthracite-600" /> or <div className="h-px flex-1 bg-anthracite-600" />
            </div>
            <a href="/auth/sso/login" className="btn-secondary w-full justify-center">
              <KeyRound size={15} /> Sign in with SSO
            </a>
          </>
        )}
      </form>
    </div>
  );
}
