import { useEffect, useState } from "react";
import { LogIn, ShieldCheck, KeyRound } from "lucide-react";
import { useAuthStore } from "../store/useAuthStore";
import HyperliteLogo from "../components/HyperliteLogo";
import { fetchSsoStatus } from "../api/client";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";

export default function LoginScreen() {
  const login = useAuthStore((s) => s.login);
  const loginWith2FA = useAuthStore((s) => s.loginWith2FA);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const storeError = useAuthStore((s) => s.error);
  const [error, setError] = useState(storeError || "");
  const [loading, setLoading] = useState(false);

  // The button only appears if an IdP is configured AND enabled on the server side
  // (GET /auth/sso/status, public: the sign-in screen knows nothing about anyone
  // yet). A failure in /auth/sso/callback comes back here through "?sso_error=..."
  // (see app/routers/sso.py) instead of a raw error page.
  const [ssoEnabled, setSsoEnabled] = useState(false);
  useEffect(() => {
    fetchSsoStatus().then((r) => setSsoEnabled(!!r.enabled)).catch(() => {});
    const params = new URLSearchParams(window.location.search);
    const ssoError = params.get("sso_error");
    if (ssoError) {
      setError(ssoError);
      window.history.replaceState({}, "", window.location.pathname);
    }
  }, []);

  // 2FA: when /auth/login returns require_2fa, we switch to a second step (TOTP code
  // entry) instead of showing the password form again. preAuthToken carries the
  // proof that the password was correct, valid for 5 minutes (see security.py).
  const [preAuthToken, setPreAuthToken] = useState(null);
  const [code, setCode] = useState("");

  async function onSubmit(e) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const result = await login(username, password);
      if (result.require2FA) {
        setPreAuthToken(result.preAuthToken);
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function onSubmit2FA(e) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      await loginWith2FA(preAuthToken, code, username);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  if (preAuthToken) {
    return (
      <div className="flex h-screen items-center justify-center bg-background">
        <Card className="w-full max-w-sm animate-in fade-in-0 zoom-in-95 duration-200 p-6">
          <form onSubmit={onSubmit2FA}>
            <div className="mb-5 flex items-center gap-2">
              <ShieldCheck size={22} className="text-accent-blue" />
              <span className="text-base font-semibold tracking-wide text-foreground">Two-step verification</span>
            </div>
            <p className="mb-3 text-sm text-muted-foreground">
              Enter the 6-digit code generated by your authenticator app.
            </p>
            <Input
              aria-label="6-digit verification code" autoComplete="one-time-code"
              className="text-center text-lg tracking-[0.4em]" autoFocus inputMode="numeric" maxLength={6}
              value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
            />
            {error && <p role="alert" className="mt-3 text-sm text-status-error animate-in fade-in-0 slide-in-from-top-1 duration-150">{error}</p>}
            <Button type="submit" disabled={loading || code.length !== 6} className="mt-5 w-full justify-center">
              <ShieldCheck /> {loading ? "Verifying..." : "Verify"}
            </Button>
            <Button
              type="button" variant="link" className="mt-1 w-full text-muted-foreground"
              onClick={() => { setPreAuthToken(null); setCode(""); setError(""); }}
            >
              Back
            </Button>
          </form>
        </Card>
      </div>
    );
  }

  return (
    <div className="flex h-screen items-center justify-center bg-background">
      <Card className="w-full max-w-sm animate-in fade-in-0 zoom-in-95 duration-200 p-6">
        <form onSubmit={onSubmit}>
          <div className="mb-5 flex items-center gap-2">
            <HyperliteLogo size={32} className="rounded-md" />
            <span className="text-base font-semibold tracking-wide text-foreground">HYPERLITE</span>
          </div>

          <div className="mb-3">
            <Label htmlFor="login-username" className="mb-1.5 text-xs font-medium text-muted-foreground">Username</Label>
            <Input id="login-username" autoComplete="username" autoFocus value={username} onChange={(e) => setUsername(e.target.value)} />
          </div>

          <div>
            <Label htmlFor="login-password" className="mb-1.5 text-xs font-medium text-muted-foreground">Password</Label>
            <Input id="login-password" autoComplete="current-password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
          </div>

          {error && <p role="alert" className="mt-3 text-sm text-status-error animate-in fade-in-0 slide-in-from-top-1 duration-150">{error}</p>}

          <Button type="submit" disabled={loading} className="mt-5 w-full justify-center">
            <LogIn /> {loading ? "Signing in..." : "Sign in"}
          </Button>

          {ssoEnabled && (
            <>
              <div className="my-4 flex items-center gap-3 text-xs text-muted-foreground">
                <Separator className="flex-1" /> or <Separator className="flex-1" />
              </div>
              <Button asChild variant="secondary" className="w-full justify-center">
                <a href="/auth/sso/login">
                  <KeyRound /> Sign in with SSO
                </a>
              </Button>
            </>
          )}
        </form>
      </Card>
    </div>
  );
}
