#!/bin/bash
# Runs CHROOTED in the target system (through d-i preseed/late_command +
# in-target, see preseed.cfg) right after the base Debian installation and the
# packages listed in pkgsel/include (libvirt/KVM/python3/curl/gnupg are already
# present at this stage).
#
# Hyperlite is not embedded as source in the ISO: it is installed directly from
# the published APT repository (see installer/build-apt-repo.sh), exactly as an
# administrator would do by typing the command by hand. A fresh appliance is
# therefore NATIVELY managed by apt from its first boot, and updates never
# require rebuilding or reflashing an ISO.
#
# The repository location comes from installer/apt-source.conf, embedded next to this
# script by build-iso.sh.
set -e

log() { echo "[hyperlite-postinstall] $*"; }

INSTALLER_DIR=/root/hyperlite-installer
APP_DIR=/root/hyperlite
# Fall back to the constant "hyperlite" if the file is missing or empty: it is
# written by partman-auto.sh (preseed/include_command), a mechanism whose
# reliability proved uncertain for other values (see preseed.cfg). Since the
# password is fixed anyway, there is no reason to let the whole script fail
# here (set -e) if that file is missing.

log "=== 1/6: preparing APT ==="
# The Debian installer AUTOMATICALLY adds the installation CD-ROM as an APT
# source in /etc/apt/sources.list (standard, documented installer behaviour).
# `apt-get update` then fails globally with "The repository 'cdrom://...' does
# not have a Release file" even if every other source works, because apt returns
# an error as soon as ANY single source fails. The line is removed first.
sed -i '/^deb cdrom:/d' /etc/apt/sources.list

# The repository location comes from installer/apt-source.conf (the single source of truth),
# embedded in the ISO by build-iso.sh.
# shellcheck disable=SC1091
[ -f "$INSTALLER_DIR/apt-source.conf" ] && . "$INSTALLER_DIR/apt-source.conf"
if [ -z "${HYPERLITE_APT_URL:-}" ]; then
    log "ERROR: no repository location (apt-source.conf is missing from the installer)"
    exit 1
fi
KEYRING=/usr/share/keyrings/hyperlite-archive-keyring.gpg

install_repository_source() {
    # Source used for FUTURE updates only. The installation itself does not depend
    # on it (see below), because a CDN-hosted repository such as GitHub Pages can
    # transiently serve InRelease and Packages out of sync.
    if [ ! -s "$KEYRING" ]; then
        if [ -s "$INSTALLER_DIR/hyperlite-archive-keyring.asc" ]; then
            gpg --dearmor < "$INSTALLER_DIR/hyperlite-archive-keyring.asc" > "$KEYRING"
        else
            curl -fsSL "$HYPERLITE_APT_URL/hyperlite-archive-keyring.asc" | gpg --dearmor > "$KEYRING"
        fi
    fi
    echo "deb [signed-by=$KEYRING] $HYPERLITE_APT_URL stable main" > /etc/apt/sources.list.d/hyperlite.list
}

# Debian's own mirrors are needed for the dependencies; retry a few times.
ok=0
for attempt in 1 2 3 4 5; do
    if apt-get update; then ok=1; break; fi
    log "apt-get update failed (attempt $attempt/5), retrying in 15 s"
    sleep 15
done
[ "$ok" = 1 ] || { log "ERROR: apt-get update failed (no network or Debian mirror unreachable?)"; exit 1; }

# Record which ISO build installed this machine (version, source commit, build date).
[ -f "$INSTALLER_DIR/build-info" ] && cp "$INSTALLER_DIR/build-info" /etc/hyperlite-build-info

log "=== 2/6: installing Hyperlite ==="
# The package is embedded in the ISO: installing it from the local file makes the
# installation independent of the Hyperlite repository. Dependencies still come
# from the Debian mirrors. The package postinst does all the application work
# (venv, requirements, secrets specific to THIS machine, systemd service).
LOCAL_DEB=$(ls "$INSTALLER_DIR"/hyperlite_*_amd64.deb 2>/dev/null | tail -1 || true)
if [ -n "$LOCAL_DEB" ]; then
    log "installing the embedded package: $(basename "$LOCAL_DEB")"
    DEBIAN_FRONTEND=noninteractive apt-get install -y "$LOCAL_DEB"
    install_repository_source || log "WARNING: could not configure the Hyperlite repository for future updates ($HYPERLITE_APT_URL)"
else
    log "no embedded package, installing from the repository $HYPERLITE_APT_URL"
    install_repository_source
    apt-get update || { log "ERROR: cannot read the Hyperlite repository $HYPERLITE_APT_URL"; exit 1; }
    DEBIAN_FRONTEND=noninteractive apt-get install -y hyperlite
fi

log "=== 3/6: Hyperlite admin account ==="
# The Linux root password is the one chosen by the person running the installer
# (the installer asks for it). The Hyperlite `admin` account gets the random
# initial password generated by the package (stored in .env and shown on the
# console banner).

# systemctl is restrained by policy-rc.d inside the installation chroot
# ("Running in chroot, ignoring command 'start'", standard and INTENDED Debian
# behaviour during an installation, not something that can be fixed), so the
# service has never really started, and the database (schema + admin account,
# normally created by seed_admin() on the first start of the application) does
# not exist yet at this stage. seed_admin() (app/core/seed.py) is therefore
# called directly HERE instead of waiting for a start that cannot happen in this
# context: it is idempotent (it does nothing if an admin already exists, so it
# is harmless if the real first start, later and outside the chroot, calls it
# again) and already reads HYPERLITE_INITIAL_ADMIN_PASSWORD from the
# environment, so it creates the DB AND the admin account with the right
# password in a single operation.
set -a
# shellcheck disable=SC1091
. "$APP_DIR/.env"
set +a
"$APP_DIR/venv/bin/python3" -c "
import sys; sys.path.insert(0, '$APP_DIR')
from app.core.seed import seed_admin
seed_admin()
"

# By default Debian does NOT allow root password login over SSH (key only,
# implicit PermitRootLogin=prohibit-password): without this file, the password
# shown by write-motd.sh would only work on the local console, not over SSH.
cat > /etc/ssh/sshd_config.d/hyperlite.conf <<'EOF'
PermitRootLogin yes
PasswordAuthentication yes
EOF

# nfs-kernel-server: the Debian package enables it by default at installation,
# which would expose an NFS service listening on every appliance even with no
# export configured. It is disabled here: a node that really wants to serve NFS
# re-enables it itself when configuring an export (not managed by the Hyperlite
# UI for now, only the netfs CLIENT is).
systemctl disable nfs-server.service 2>/dev/null || true

log "=== 4/6: libvirt (default NAT network) ==="
systemctl enable libvirtd.service
# The "default" virtual network (NAT, virbr0) is defined by the
# libvirt-daemon-system package but is not always started/autostarted depending
# on the distribution: it is forced explicitly so that VMs have a working
# network from the first boot, with no manual step.
virsh net-autostart default 2>/dev/null || true
virsh net-start default 2>/dev/null || true

log "=== 5/6: restart (up-to-date password/MOTD) ==="
# The service has already been started ONCE by the package postinst (step 2
# above), with the former random admin password. A restart regenerates the MOTD
# (ExecStartPre, see hyperlite.service) with the FINAL password written in
# step 3, so the welcome banner shows the right value from the first login.
systemctl restart hyperlite.service

log "=== 6/6: cleanup ==="
# The clear-text password copied from the live environment is erased: it only
# remains as a hash (Hyperlite DB) and in /root/.hyperlite-initial-password
# (the same file, an explicit purpose, rather than a generically named file
# forgotten in an installer directory).

log "done"
