#!/bin/bash
# Runs CHROOTED in the target system (through d-i preseed/late_command +
# in-target, see preseed.cfg) right after the base Debian installation and the
# packages listed in pkgsel/include (libvirt/KVM/python3/curl/gnupg are already
# present at this stage).
#
# Hyperlite is not embedded as source in the ISO: it is installed directly from
# the published APT repository (see installer/build-apt-repo.sh), exactly as an
# administrator would do by typing the command by hand. A fresh appliance is
# therefore NATIVELY managed by apt from its first boot, and updates never
# require rebuilding or reflashing an ISO.
#
# The repository location is configurable: build-iso.sh writes it to
# apt-source.conf next to this script when HYPERLITE_APT_URL is set while
# building the ISO. Without it, the public repository is used.
set -e

log() { echo "[hyperlite-postinstall] $*"; }

INSTALLER_DIR=/root/hyperlite-installer
APP_DIR=/root/hyperlite
# Fall back to the constant "hyperlite" if the file is missing or empty: it is
# written by partman-auto.sh (preseed/include_command), a mechanism whose
# reliability proved uncertain for other values (see preseed.cfg). Since the
# password is fixed anyway, there is no reason to let the whole script fail
# here (set -e) if that file is missing.

log "=== 1/6: Hyperlite APT repository ==="
HYPERLITE_APT_URL="https://twikles.github.io/hyperlite"
# shellcheck disable=SC1091
[ -f "$INSTALLER_DIR/apt-source.conf" ] && . "$INSTALLER_DIR/apt-source.conf"
log "repository: $HYPERLITE_APT_URL"

# The Debian installer AUTOMATICALLY adds the installation CD-ROM as an APT
# source in /etc/apt/sources.list (standard, documented installer behaviour,
# not specific to this repository). `apt-get update` then fails globally with
# "The repository 'cdrom://...' does not have a Release file" EVEN IF all the
# other sources (including ours) are fetched successfully, because apt returns
# an error as soon as ANY single source fails. The line is removed before any
# apt-get update: the CD-ROM is no longer needed as a source once the standard
# Debian repositories and ours are configured.
sed -i '/^deb cdrom:/d' /etc/apt/sources.list

# Note on the repository host: GitHub Pages is a multi-node CDN with NO strong
# consistency guarantee between related files published in the same commit
# (InRelease and Packages can be served out of sync for a long time), which
# makes `apt-get update` fail with "File has unexpected size". When that
# matters, serve the repository directly (a single origin, no CDN) and point
# HYPERLITE_APT_URL at it when building the ISO.
curl -fsSL "$HYPERLITE_APT_URL/hyperlite-archive-keyring.asc" | gpg --dearmor -o /usr/share/keyrings/hyperlite-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hyperlite-archive-keyring.gpg] $HYPERLITE_APT_URL stable main" > /etc/apt/sources.list.d/hyperlite.list
apt-get update || { log "ERROR: apt-get update failed (is $HYPERLITE_APT_URL reachable?)"; exit 1; }

log "=== 2/6: installing Hyperlite (apt install hyperlite) ==="
# The package postinst (installer/deb/postinst) does all the application work
# itself: it creates the venv, installs requirements.txt, generates secrets
# specific to THIS machine (.env absent = first installation), and installs,
# enables and starts the systemd service. Nothing more to do here for the
# application itself.
DEBIAN_FRONTEND=noninteractive apt-get install -y hyperlite

log "=== 3/6: Hyperlite admin account ==="
# The Linux root password is the one chosen by the person running the installer
# (the installer asks for it). The Hyperlite `admin` account gets the random
# initial password generated by the package (stored in .env and shown on the
# console banner).

# systemctl is restrained by policy-rc.d inside the installation chroot
# ("Running in chroot, ignoring command 'start'", standard and INTENDED Debian
# behaviour during an installation, not something that can be fixed), so the
# service has never really started, and the database (schema + admin account,
# normally created by seed_admin() on the first start of the application) does
# not exist yet at this stage. seed_admin() (app/core/seed.py) is therefore
# called directly HERE instead of waiting for a start that cannot happen in this
# context: it is idempotent (it does nothing if an admin already exists, so it
# is harmless if the real first start, later and outside the chroot, calls it
# again) and already reads HYPERLITE_INITIAL_ADMIN_PASSWORD from the
# environment, so it creates the DB AND the admin account with the right
# password in a single operation.
set -a
# shellcheck disable=SC1091
. "$APP_DIR/.env"
set +a
"$APP_DIR/venv/bin/python3" -c "
import sys; sys.path.insert(0, '$APP_DIR')
from app.core.seed import seed_admin
seed_admin()
"

# By default Debian does NOT allow root password login over SSH (key only,
# implicit PermitRootLogin=prohibit-password): without this file, the password
# shown by write-motd.sh would only work on the local console, not over SSH.
cat > /etc/ssh/sshd_config.d/hyperlite.conf <<'EOF'
PermitRootLogin yes
PasswordAuthentication yes
EOF

# nfs-kernel-server: the Debian package enables it by default at installation,
# which would expose an NFS service listening on every appliance even with no
# export configured. It is disabled here: a node that really wants to serve NFS
# re-enables it itself when configuring an export (not managed by the Hyperlite
# UI for now, only the netfs CLIENT is).
systemctl disable nfs-server.service 2>/dev/null || true

log "=== 4/6: libvirt (default NAT network) ==="
systemctl enable libvirtd.service
# The "default" virtual network (NAT, virbr0) is defined by the
# libvirt-daemon-system package but is not always started/autostarted depending
# on the distribution: it is forced explicitly so that VMs have a working
# network from the first boot, with no manual step.
virsh net-autostart default 2>/dev/null || true
virsh net-start default 2>/dev/null || true

log "=== 5/6: restart (up-to-date password/MOTD) ==="
# The service has already been started ONCE by the package postinst (step 2
# above), with the former random admin password. A restart regenerates the MOTD
# (ExecStartPre, see hyperlite.service) with the FINAL password written in
# step 3, so the welcome banner shows the right value from the first login.
systemctl restart hyperlite.service

log "=== 6/6: cleanup ==="
# The clear-text password copied from the live environment is erased: it only
# remains as a hash (Hyperlite DB) and in /root/.hyperlite-initial-password
# (the same file, an explicit purpose, rather than a generically named file
# forgotten in an installer directory).

log "done"
